[workspace]

members = [
    "test-lib",
    "test-bin",
    "nested/lib",
]

[workspace.metadata.raze]
workspace_path = "//cargo"
genmode = "Remote"
default_gen_buildrs = true
experimental_api = true
render_package_aliases = false
